theme: jekyll-theme-tactile
title: Uwa's lighting mods
comments: true

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: https-uwa-lights
