theme: jekyll-theme-tactile
title: Uwa's lighting mods
description: Updated aircraft lighting for Microsoft Flight Simulator 2020
comments: true

<link rel="stylesheet" href="FS2020/assets/css/style.scss">
